sudo: required
dist: trusty
language: generic

env:
  global:
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=snp_prbt.rosinstall
    - ROSDEP_SKIP_KEYS="pilz_modbus pilz_sto_modbus_adapter pilz_trajectory_generation prbt_pg70_support"
    - BEFORE_SCRIPT="wget -q https://download.ensenso.com/s/ensensosdk/download?files=ensenso-sdk-2.2.65-x64.deb -O /tmp/ensenso.deb && dpkg -i /tmp/ensenso.deb"
    - DOCKER_RUN_OPTS="-e ENSENSO_INSTALL=/opt/ensenso"
    - ADDITIONAL_DEBS="pkg-config"
    - CATKIN_CONFIG="--no-install"
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros

install:
  - sudo apt-get -y install xvfb # gtk2-engines-pixbuf
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - xvfb-run .ci_config/travis.sh
