<?xml version="1.0" ?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="acf_111_04_with_grinder" params="parent *origin prefix:=${''} extent_factor:=${0.7} contact:=${'true'}">

    <xacro:property name="acf_110_04_compressed" value="0.1905"/>
    <xacro:property name="grinder" value="0.085"/>
    <xacro:property name="tool_compressed" value="${acf_110_04_compressed + grinder}"/>
    <xacro:property name="tool_stroke" value="0.0355"/>
    <xacro:property name="safety_dist" value="0.04"/>

    <link name="${prefix}acf_111_04_and_grinder">
      <inertial>
        <origin xyz="0 0 0.145" rpy="0 0 0" />
        <mass value="5" />
        <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.02" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://snp_psir_description/meshes/acf_with_grinder/acf_111_04_with_grinder.STL" />
        </geometry>
        <material name="">
          <color rgba="0.8 0.8 0.9 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.16" rpy="0 0 0" />
        <geometry>
          <cylinder length="${tool_compressed + tool_stroke}" radius="0.1"/>
        </geometry>
      </collision>
      <!-- Attached cable -->
      <collision>
        <origin xyz="-0.11 0.053 0.035" rpy="0 ${pi/2} ${-0.42}" />
        <geometry>
          <cylinder length="0.08" radius="0.014" />
        </geometry>
      </collision>
      <!-- air pumper -->
      <collision>
        <origin xyz="-0.10 0.01 0.25" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="0.1" radius="0.02" />
        </geometry>
      </collision>
    </link>

    <!--joint between fixture and polisher-->
    <joint name="${prefix}acf_111_04_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${prefix}acf_111_04_and_grinder" />
      <axis xyz="0 0 0" />
    </joint>

    <link name="${prefix}tcp_frame" />
    <joint name="${prefix}tip_joint" type="fixed">
      <parent link="${prefix}acf_111_04_and_grinder"/>
      <child link="${prefix}tcp_frame"/>
      <!-- Working point at middle of stroke -->
      <xacro:if value="${contact}">
        <origin xyz="0 0 ${tool_compressed + extent_factor * tool_stroke}" rpy="0 0 0"/>
      </xacro:if>
      <xacro:unless value="${contact}">
        <origin xyz="0 0 ${tool_compressed + tool_stroke + safety_dist}" rpy="0 0 0"/>
      </xacro:unless>
    </joint>

  </xacro:macro>
</robot>
