controller_list:
  - name: fake_manipulator_controller
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
  - name: fake_manipulator_ensenso_controller
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
  - name: fake_manipulator_asus_controller
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
  - name: fake_manipulator_tcp_controller
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6