#!/usr/bin/env python

import rospy
from moveit_commander import MoveItCommanderException
from snp_py.snp_interface import SNPCommander

if __name__ == "__main__":
    rospy.init_node("snp_test")
    move_group = rospy.get_param("/godel_process_planning/blend_group")
    SNP = SNPCommander(move_group, planner="PTP")
    try:
        SNP.move_home()
        SNP.surface_detection()
        SNP.select_surface()
        SNP.plan()
        SNP.get_available_motion_plan()
        SNP.select_motion_plan(simulate=True)
        SNP.select_motion_plan(simulate=False)

    except (MoveItCommanderException, rospy.ROSException, rospy.ServiceException) as e:
        rospy.logerr("SNP failed due to %s" % e)
